[package]
name = "sgx-dev"
version = "0.1.0"
authors = ["Paul O'Leary <paul@eluv.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sgx-isa = { version = "0.2", features = ["sgxstd"] }
rand = "0.6.4"